### List all members
GET http://rbc.dev/api/auth/members


### Create a new member - SUCCESS
POST http://rbc.dev/api/auth/members
Content-Type: application/json

{
    "crmId": "dtf3",
    "email": "james@brown.com",
    "firstName": "James",
    "lastName": "Brown"
}

### Create a new member - FAIL
POST http://rbc.dev/api/auth/members
Content-Type: application/json

{
    "_id": ""
}
