apiVersion: skaffold/v2beta27
kind: Config
deploy:
  helm:
    releases:
    - name: rbc
      version: ~0.1.6
      chartPath: charts/rbc
      namespace: rbc
      createNamespace: true
      setValues:
        tags.rbc: false
    - name: rbc-auth
      version: ~0.1.6
      chartPath: charts/subcharts/rbc-auth
      namespace: rbc
      artifactOverrides:
        imageKey: curioushuman/rbc-auth
      imageStrategy:
        helm: {}
build:
  local:
    push: false
  artifacts:
    - image: curioushuman/rbc-auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
          - src: 'src/**/*.http'
            dest: .
          - src: 'src/**/*.md'
            dest: .
    # - image: curioushuman/rbc-subscriptions
    #   context: subscriptions
    #   docker:
    #     dockerfile: Dockerfile
    #     target: development
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    #       - src: 'src/**/*.http'
    #         dest: .
    #       - src: 'src/**/*.md'
    #         dest: .
