apiVersion: skaffold/v2beta27
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
      # - ./infra/k8s-monitor/*
build:
  local:
    push: false
  artifacts:
    - image: curioushuman/rbc-auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
          - src: 'src/**/*.http'
            dest: .
          - src: 'src/**/*.md'
            dest: .
    - image: curioushuman/rbc-subscriptions
      context: subscriptions
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
          - src: 'src/**/*.http'
            dest: .
          - src: 'src/**/*.md'
            dest: .
