apiVersion: skaffold/v2beta27
kind: Config
deploy:
  helm:
    releases:
    - name: rbc-subscriptions
      chartPath: ../charts/subcharts/rbc-subscriptions
      namespace: rbc-subscriptions
      createNamespace: true
      artifactOverrides:
        imageKey: curioushuman/rbc-subscriptions
      imageStrategy:
        helm: {}
build:
  local:
    push: false
  artifacts:
    - image: curioushuman/rbc-subscriptions
      context: .
      docker:
        dockerfile: Dockerfile
        target: development
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
          - src: 'src/**/*.http'
            dest: .
          - src: 'src/**/*.md'
            dest: .
