apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: init-kafka
          image: curioushuman/rbc-base
          env:
            # TODO store these in args or values
            - name: KAFKA_BROKERS
              value: 'kafka-srv:9092'
            - name: KAFKA_GROUPID
              value: 'auth-consumer-client'
          command: ['sh', '-c', "until node /usr/src/init/dist/src/index.js -c kafka; do sleep 2; done"]
        - name: init-auth-mongo
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup auth-mongo-srv.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo auth waiting for auth-mongo-srv; sleep 2; done"]
      containers:
        - name: auth
          image: curioushuman/rbc-auth
          env:
            - name: MONGODB_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: PORT
              value: '3000'
            - name: KAFKA_BROKERS
              value: 'kafka-srv:9092'
            - name: KAFKA_GROUPID
              value: 'auth-consumer-client'
            # - name: JWT_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: jwt-secret
            #       key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
