apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: obsidiandynamics/kafka
          env:
            - name: KAFKA_LISTENERS
              value: 'INTERNAL://:29092,EXTERNAL://:9092'
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: 'INTERNAL'
            - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT
              value: '6000'
            - name: KAFKA_RESTART_ATTEMPTS
              value: '10'
            - name: KAFKA_RESTART_DELAY
              value: '5'
            - name: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
              value: '0'
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-srv
spec:
  selector:
    app: kafka
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: server
      protocol: TCP
      port: 9092
      targetPort: 9092
