apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriptions
  template:
    metadata:
      labels:
        app: subscriptions
    spec:
      containers:
        - name: subscriptions
          image: curioushuman/rbc-subscriptions
          env:
            - name: MONGODB_URI
              value: 'mongodb://subscriptions-mongo-srv:27017/subscriptions'
            - name: PORT
              value: '3001'
            # - name: JWT_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: jwt-secret
            #       key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: subscriptions-srv
spec:
  selector:
    app: subscriptions
  ports:
    - name: subscriptions
      protocol: TCP
      port: 3001
      targetPort: 3001
