apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop
          env:
            - name: KAFKA_BROKERCONNECT
              value: 'kafka:29092'
            - name: JVM_OPTS
              value: '-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify'
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-srv
spec:
  selector:
    app: kafdrop
  ports:
    - name: gui
      protocol: TCP
      port: 9000
      targetPort: 9000
